### PR TITLE
fix(schema): Correctly validate schema version

### LINKED ISSUE #2493: Schema validation fails for schema version 2
**Describe the bug**
I can't use the dashboard reporter to upload reports since the tool was updated to `3.8.1`.
The same report with tool version `3.7.1` is working.

**Logs**
I get the following error in the [Github Build Pipeline](https://github.com/Testably/Testably.Architecture.Rules/actions/runs/4900499091/jobs/8751189918):
```
All mutants have been tested, and your mutation score has been calculated
…[07:56:25 ERR] Failed to upload report to the dashboard at https://dashboard.stryker-mutator.io/api/reports/github.com/Testably/Testably.Architecture.Rules/main?module=Testably.Architecture.Rules
System.Net.Http.HttpRequestException: Response status code does not indicate success: [40](https://github.com/Testably/Testably.Architecture.Rules/actions/runs/4900499091/jobs/8751189918#step:5:41)0 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Stryker.Core.Clients.DashboardClient.PublishReport(JsonReport report, String version)
[07:56:25 ERR] Uploading to stryker dashboard failed...`
```
When I revert back to v3.7.1 (`dotnet tool install dotnet-stryker --tool-path ../tools --version 3.7.1`) the report gets successfully uploaded:
```
All mutants have been tested, and your mutation score has been calculated
…Hint: by passing "--open-report:dashboard or -o:dashboard" the report will open 
automatically once Stryker is done.

Your report has been uploaded at:
https://dashboard.stryker-mutator.io/reports/github.com/Testably/Testably.Archit
ecture.Rules/topic/vb/change-stryker-version?module=Testably.Architecture.Rules
You can open it in your browser of choice.
```

**Expected behavior**
The report should be uploaded to https://dashboard.stryker-mutator.io/.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Type of project: core
 - Framework Version net6.0
 - Stryker Version 3.8.1

**Additional context**
In my other project Stryker also no longer uploads the dashboard report, but it [shows a different error message](https://github.com/Testably/Testably.Abstractions/actions/runs/4902459842/jobs/8754314766):
```
[16:04:59 INF] Initial testrun started.
[16:05:15 INF] Time Elapsed 00:01:13.8443548
Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Stryker.Core.Initialisation.ProjectMutator.EnrichTestProjectsWithTestInfo(InitialTestRun initialTestRun, TestProjectsInfo testProjectsInfo)
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(StrykerOptions options, IReporter reporters, IEnumerable`1 solutionProjects)
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator)
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 93
   at Stryker.CLI.StrykerCli.<>c__DisplayClass10_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 68
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 74
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 14
/home/runner/work/_temp/e6b4cac3-c1[27](https://github.com/Testably/Testably.Abstractions/actions/runs/4902459842/jobs/8754314766#step:5:28)-4f6d-b5f5-cf92c89680a7.sh: line 2:  1858 Aborted                 (core dumped) ../../tools/dotnet-stryker -f ../.github/stryker/Stryker.Config.Testing.json -v "${GITHUB_REF#refs/heads/}" -r "Dashboard" -r "cleartext"
Error: Process completed with exit code 1[34](https://github.com/Testably/Testably.Abstractions/actions/runs/4902459842/jobs/8754314766#step:5:35).
```

### LINKED ISSUE #2495: theme-changed CI browser tests failing on windows since some days
https://github.com/stryker-mutator/mutation-testing-elements/actions/runs/4882628041

### PR DESCRIPTION
**Pull request by rouke-broersma**
fix #2493 
fix #2495 

image

@nicojs Is this how we want to deal with this breaking change? Since it's a forward breaking change accepting V1 and V2 schemas in the same schema should be fine right?

I don't understand how the e2e test for v2 schema I added didn't catch this in the dashboard...

### CODE REVIEW

**Comment by rouke-broersma** [comment]
metrics scala does not seem to accept the Pending state even though it was added here: https://github.com/stryker-mutator/mutation-testing-elements/blob/3780eb7ca78e70f4cbe6f6b6bf034efc1f73d147/packages/metrics-scala/metrics/src/main/scala/mutationtesting/MutantStatus.scala#L15

I also see that the schemaVersion is still `1` in the mutationtestresult: https://github.com/stryker-mutator/mutation-testing-elements/blob/master/packages/metrics-scala/metrics/src/main/scala/mutationtesting/mutationTestResult.scala#L33

Should that be updated to 2 @hugo-vrijswijk?

**Comment by hugo-vrijswijk** [comment]
> metrics scala does not seem to accept the Pending state even though it was added here: https://github.com/stryker-mutator/mutation-testing-elements/blob/3780eb7ca78e70f4cbe6f6b6bf034efc1f73d147/packages/metrics-scala/metrics/src/main/scala/mutationtesting/MutantStatus.scala#L15

It looks like it wasn't fully added to the JSON codec here, I can't add it today, but feel free to add it: https://github.com/stryker-mutator/mutation-testing-elements/blob/master/packages/metrics-scala/circe/src/main/scala/mutationtesting/circe.scala#L110

> I also see that the schemaVersion is still `1` in the mutationtestresult: https://github.com/stryker-mutator/mutation-testing-elements/blob/master/packages/metrics-scala/metrics/src/main/scala/mutationtesting/mutationTestResult.scala#L33
> 
> Should that be updated to 2 @hugo-vrijswijk?

Yes, though it's a default property so can be overridden if needed

**Comment by rouke-broersma** [comment]
I have no clue why the integration tests are failing.. See: #2495

**Comment by rouke-broersma** [comment]
```
mutation-testing-elements: Chrome Headless 112.0.5615.165 (Linux x86_64) MutationTestReportAppComponent theme property should trigger a `theme-changed` event when the theme changes FAILED
mutation-testing-elements: 	AssertionError: expected ' #18181b' to equal '#18181b'
mutation-testing-elements: 	    at Context.<anonymous> (/tmp/_karma_webpack_556966/commons.js:42942:68)
mutation-testing-elements: Chrome Headless 112.0.5615.165 (Linux x86_64): Executed 20 of 242 (1 FAILED) (0 secs / 0.14 secs)
mutation-testing-elements: Chrome Headless 112.0.5615.165 (Linux x86_64) MutationTestReportAppComponent theme property should trigger a `theme-changed` event when the theme changes during init FAILED
mutation-testing-elements: 	AssertionError: expected ' #18181b' to equal '#18181b'
mutation-testing-elements: 	    at Context.<anonymous> (/tmp/_karma_webpack_556966/commons.js:42952:68)
mutation-testing-elements: Chrome Headless 112.0.5615.165 (Linux x86_64): Executed 21 of 242 (2 FAILED) (0 secs / 0.144 secs)
mutation-testing-elements: Chrome Headless 112.0.5615.165 (Linux x86_64) MutationTestReportAppComponent theme property themeBackgroundColor should show light theme-color on light theme FAILED
mutation-testing-elements: 	AssertionError: expected ' #fff' to equal '#fff'
```


WHYYYY COME ON

**Review by hugo-vrijswijk — APPROVED** [review]

**Pull request merged**
