### PR TITLE
feat(mutant-view): show status reason in drawer

### PR DESCRIPTION
**Pull request by nicojs**
Show the `statusReason` field inside the mutant drawer summary with a detective (🕵️‍♀️) emoji

status reason

### CODE REVIEW

**Comment by nicojs** [comment]
For some reason (pun intended), we forgot about the status reason. Was wondering why reasons didn't show up in Stryker's reports. Turns out this is the reason.

Great reasoning, no? 🕵️‍♀️

**Comment by hugo-vrijswijk** [comment]
Could you add some screenshot tests?

**Comment by nicojs** [comment]
This is a very good point. I rushed this feature. When I started to implement the test, I saw a flaw. I didn't put the `statusReason` in its own `<h6 class="pe-4">`, which adds much-needed padding.

I've started te update screenshots actions, so screenshots should update within the next 10 mins.

**Comment by nicojs** [comment]
Linux:

**Comment by nicojs** [comment]
I've added a "title" attribute 🤯
image

**Review by hugo-vrijswijk — APPROVED** [review]
Nice!

**Pull request merged**
