### PR TITLE
build: add build for node 8

### PR DESCRIPTION
**Pull request by simondel**

### CODE REVIEW

**Comment by nicojs** [comment]
Why is this needed? Mutation-testing-elements runs in the browser, not node, right?

**Comment by simondel** [comment]
Good point. Kill it!

**Comment by nicojs** [comment]
It's a bit harsh to kill mutation-testing-elements just because it runs a browser. I mean, it's not his fault. 🤔

**Comment by hugo-vrijswijk** [comment]
Alternatively, metrics could run in node

**Comment by nicojs** [comment]
Yeah good point.

**Pull request merged**
