### PR TITLE
fix(elements-table): transition score colors

### PR DESCRIPTION
**Pull request by hugo-vrijswijk**
Looks nice with the real-time updates 😃

image

### CODE REVIEW

**Comment by nicojs** [comment]
Do you have an example? I tried to run it locally with the "🚀 Realtime reporting example" but couldn't see the difference.

**Comment by hugo-vrijswijk** [comment]
Yeah the realtime reporting example always pushes 'Killed' mutants, so it's pretty difficult to see as it's just about always green. You can see it better when switching directories (and the same line in the table has a different colour)

**Comment by xandervedder** [comment]
> Do you have an example? I tried to run it locally with the "🚀 Realtime reporting example" but couldn't see the difference.
It might be nice if the example sends a random status 🤔

**Comment by hugo-vrijswijk** [comment]
> > Do you have an example? I tried to run it locally with the "🚀 Realtime reporting example" but couldn't see the difference.
> 
> It might be nice if the example sends a random status 🤔

The issue is then that you approach a score of 50% 😃

**Comment by rouke-broersma** [comment]
Looks nice!

**Pull request merged**
